# Generated by Django 4.2.9 on 2025-12-09 22:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('roastery_name', models.CharField(db_index=True, max_length=200)),
                ('name_normalized', models.CharField(db_index=True, editable=False, max_length=200)),
                ('roastery_normalized', models.CharField(db_index=True, editable=False, max_length=200)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('processing', models.CharField(choices=[('washed', 'Washed'), ('natural', 'Natural/Dry'), ('honey', 'Honey'), ('anaerobic', 'Anaerobic'), ('other', 'Other')], default='washed', max_length=50)),
                ('roast_profile', models.CharField(choices=[('light', 'Light'), ('medium_light', 'Medium-Light'), ('medium', 'Medium'), ('medium_dark', 'Medium-Dark'), ('dark', 'Dark')], default='medium', max_length=50)),
                ('roast_date', models.DateField(blank=True, null=True)),
                ('brew_method', models.CharField(choices=[('espresso', 'Espresso'), ('filter', 'Filter/Pour Over'), ('french_press', 'French Press'), ('aeropress', 'AeroPress'), ('moka', 'Moka Pot'), ('cold_brew', 'Cold Brew'), ('other', 'Other'), ('automat', 'Automat')], default='filter', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tasting_notes', models.CharField(blank=True, max_length=500)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coffeebeans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeBeanVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_weight_grams', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_czk', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('price_per_gram', models.DecimalField(decimal_places=4, editable=False, max_digits=10)),
                ('purchase_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coffeebean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='beans.coffeebean')),
            ],
            options={
                'db_table': 'coffeebean_variants',
                'ordering': ['package_weight_grams'],
                'indexes': [models.Index(fields=['coffeebean', 'is_active'], name='coffeebean__coffeeb_3aee73_idx'), models.Index(fields=['price_per_gram'], name='coffeebean__price_p_f15441_idx')],
                'unique_together': {('coffeebean', 'package_weight_grams')},
            },
        ),
        migrations.AddIndex(
            model_name='coffeebean',
            index=models.Index(fields=['name'], name='coffeebeans_name_26c222_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeebean',
            index=models.Index(fields=['roastery_name'], name='coffeebeans_roaster_9e2756_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeebean',
            index=models.Index(fields=['name_normalized', 'roastery_normalized'], name='coffeebeans_name_no_f2ede2_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeebean',
            index=models.Index(fields=['avg_rating'], name='coffeebeans_avg_rat_031085_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeebean',
            index=models.Index(fields=['created_at'], name='coffeebeans_created_f96ff5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coffeebean',
            unique_together={('name_normalized', 'roastery_normalized')},
        ),
    ]
