# Generated by Django 4.2.9 on 2025-12-19 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merged_from', models.UUIDField(help_text='ID of bean that was merged (deleted)')),
                ('reason', models.TextField(blank=True)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('merged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bean_merges', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(help_text='Bean that absorbed the merged bean', on_delete=django.db.models.deletion.CASCADE, related_name='merge_targets', to='beans.coffeebean')),
            ],
            options={
                'db_table': 'bean_merge_history',
                'ordering': ['-merged_at'],
                'indexes': [models.Index(fields=['merged_from'], name='bean_merge__merged__61fb3f_idx'), models.Index(fields=['merged_at'], name='bean_merge__merged__b084af_idx')],
            },
        ),
    ]
