# Generated by Django 4.2.9 on 2025-12-09 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=True)),
                ('invite_code', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_memberships',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['group', 'role'], name='group_membe_group_i_bcefbf_idx'), models.Index(fields=['user', 'joined_at'], name='group_membe_user_id_3644a5_idx')],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupLibraryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('pinned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_group_beans', to=settings.AUTH_USER_MODEL)),
                ('coffeebean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_libraries', to='beans.coffeebean')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='groups.group')),
            ],
            options={
                'db_table': 'group_library_entries',
                'ordering': ['-pinned', '-added_at'],
                'indexes': [models.Index(fields=['group', 'pinned', 'added_at'], name='group_libra_group_i_0507ae_idx'), models.Index(fields=['group', 'added_at'], name='group_libra_group_i_188ad5_idx')],
                'unique_together': {('group', 'coffeebean')},
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['owner', 'created_at'], name='groups_owner_i_e9b8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['invite_code'], name='groups_invite__7fda49_idx'),
        ),
    ]
