# Generated by Django 4.2.9 on 2025-12-09 22:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beans', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price_czk', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='CZK', max_length=3)),
                ('package_weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('purchase_location', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('total_collected_czk', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bought_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_made', to=settings.AUTH_USER_MODEL)),
                ('coffeebean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='beans.coffeebean')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='groups.group')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='beans.coffeebeanvariant')),
            ],
            options={
                'db_table': 'purchase_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_czk', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='CZK', max_length=3)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('payment_reference', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('qr_url', models.CharField(blank=True, max_length=500)),
                ('qr_image_path', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_shares', to='purchases.purchaserecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_shares',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('amount_czk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variable_symbol', models.CharField(blank=True, db_index=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('matched_share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='purchases.paymentshare')),
            ],
            options={
                'db_table': 'bank_transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserecord',
            index=models.Index(fields=['group', 'date'], name='purchase_re_group_i_128459_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserecord',
            index=models.Index(fields=['bought_by', 'date'], name='purchase_re_bought__1e018e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserecord',
            index=models.Index(fields=['coffeebean', 'date'], name='purchase_re_coffeeb_bea9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserecord',
            index=models.Index(fields=['date'], name='purchase_re_date_f61f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserecord',
            index=models.Index(fields=['is_fully_paid'], name='purchase_re_is_full_f6da88_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentshare',
            index=models.Index(fields=['user', 'status'], name='payment_sha_user_id_af6ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentshare',
            index=models.Index(fields=['purchase', 'status'], name='payment_sha_purchas_f1490e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentshare',
            index=models.Index(fields=['payment_reference'], name='payment_sha_payment_7704db_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentshare',
            index=models.Index(fields=['status', 'created_at'], name='payment_sha_status_682bdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentshare',
            unique_together={('purchase', 'user')},
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_id'], name='bank_transa_transac_473e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['variable_symbol'], name='bank_transa_variabl_9801a8_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['is_matched', 'date'], name='bank_transa_is_matc_7e4eb1_idx'),
        ),
    ]
