# Generated by Django 4.2.9 on 2025-12-09 22:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beans', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserLibraryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_by', models.CharField(choices=[('review', 'From Review'), ('purchase', 'From Purchase'), ('manual', 'Manual Add')], default='review', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('own_price_czk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('coffeebean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_libraries', to='beans.coffeebean')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_library_entries',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'added_at'], name='user_librar_user_id_b11f09_idx'), models.Index(fields=['user', 'is_archived'], name='user_librar_user_id_1da677_idx')],
                'unique_together': {('user', 'coffeebean')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('aroma_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('flavor_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('acidity_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('body_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('aftertaste_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('brew_method', models.CharField(blank=True, max_length=50)),
                ('context', models.CharField(choices=[('personal', 'Personal'), ('group', 'Group/Team'), ('public', 'Public')], default='personal', max_length=20)),
                ('would_buy_again', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('coffeebean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beans.coffeebean')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='groups.group')),
                ('taste_tags', models.ManyToManyField(blank=True, related_name='reviews', to='reviews.tag')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coffeebean', 'rating'], name='reviews_coffeeb_e6af37_idx'), models.Index(fields=['author', 'created_at'], name='reviews_author__f98b87_idx'), models.Index(fields=['group', 'created_at'], name='reviews_group_i_133886_idx'), models.Index(fields=['created_at'], name='reviews_created_53b5d6_idx')],
                'unique_together': {('author', 'coffeebean')},
            },
        ),
    ]
